services:
  # nginx reverse proxy
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      # - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend

  # frontend
  frontend:
    image: frontend
    container_name: frontend
    restart: always
    environment:
      - VIRTUAL_HOST=${FRONTEND_DOMAIN}

  # backend
  backend:
    image: backend
    container_name: backend
    restart: always
    environment:
      - VIRTUAL_HOST=${BACKEND_DOMAIN}
      - REDIS_HOST=redis
    depends_on:
      - redis

  # redis
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  # redis server (not accessed by nginx)
  # redis-stack:
  #   image: redis/redis-stack-server:latest
  #   # command: redis-server /usr/local/etc/redis/redis.conf
  #   # volumes:
  #   #   - ./redis.conf:/usr/local/etc/redis/redis.conf
  #   ports:
  #     - "6379:6379"
  #   # environment:
  #   #   - REDIS_ARGS="--requirepass 1234"
